# version: "3.8"

# services:
#   mongodb:
#     image: mongo
#     restart: always
#     networks:
#       - app-network
#     ports:
#       - 27017:27017
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     networks:
#       - app-network
#     environment:
#       - ME_CONFIG_BASICAUTH_USERNAME=admin
#       - ME_CONFIG_BASICAUTH_PASSWORD=password
#       - ME_CONFIG_MONGODB_SERVER=mongodb

#   langat-app:
#     image: 365874841087.dkr.ecr.ap-northeast-1.amazonaws.com/langat-app:latest
#     ports:
#       - 4000:4000
#     networks:
#       - app-network
# networks:
#   app-network:
#     driver: bridge
version: "3"
services:
  langat-app:
    image: 365874841087.dkr.ecr.ap-northeast-1.amazonaws.com/langat-app:latest
    ports:
      - 4000:4000
  mongodb:
    image: mongo
    ports:
      - 0.0.0.0:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      mongodb:
        condition: service_healthy
volumes:
  mongo-data:
    driver: local
